run:
  timeout: 1m
  tests: true

linters-settings:
  errcheck:
    check-blank: true
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 30
  nakedret:
    max-func-lines: 50
  funlen:
    lines: 80
    statements: 50

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
  fast: false

output:
  format: colored-line-number
